Fixing the configure script to work on Macs
The issue was in the usage of 'sed -i' that works different on Max (BSD)
than on Linux.  Go figure.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -67,7 +67,7 @@ do
 
 	case $ac_option in
 		--toolchain)
-			$$ECHO -n "Error: --toolchain requires an argument; "
+			$ECHO -n "Error: --toolchain requires an argument; "
 			$ECHO "use, e.g., --toolchain=gnu"
 			exit 1
 			;;
@@ -284,6 +284,24 @@ do
 		--disable-writing | --disable-writing=*)
 			ENABLE_WRITING=false
 			;;
+		--ndim)
+			$ECHO -n "Error:  --ndim requires an argumet; "
+			$ECHO "use either --ndim=2 or --ndim=3"
+			exit 1
+			;;
+		--ndim=*)
+			if test "x$ac_optarg" = "x3"
+			then
+				NDIM_VALUE=3
+			elif test "x$ac_optarg" = "x2"
+			then
+				NDIM_VALUE=2
+			else
+				$ECHO -n "Error:  --ndim accepts only 2 and 3 "
+				$ECHO "as arguments"
+				exit 1
+			fi
+			;;
 		--enable-debug | --enable-debug=*)
 			if test "x$ac_optarg" = "xyes"
 			then
@@ -305,24 +323,6 @@ do
 			;;
 		--disable-profile | --disable-debug=*)
 			ENABLE_PROFILE=false
-			;;
-		--ndim)
-			$ECHO -n "Error:  --ndim requires an argumet; "
-			$ECHO "use either --ndim=2 or --ndim=3"
-			exit 1
-			;;
-		--ndim=*)
-			if test "x$ac_optarg" = "x3"
-			then
-				NDIM_VALUE=3
-			elif test "x$ac_optarg" = "x2"
-			then
-				NDIM_VALUE=2
-			else
-				$ECHO -n "Error:  --ndim accepts only 2 and 3 "
-				$ECHO "as arguments"
-				exit 1
-			fi
 			;;
 		-h | --help*)
 			SHOW_HELP=true
@@ -410,10 +410,6 @@ Optional features:
                            Default: auto.
   --with-fft-libs=LIBS     See description of --with-sprng-libs.
                            Default: auto.
-  --with-gsl-libs=LIBS     This may be used to set specific libraries of
-                           GSL, normally it should not be neccessary to
-                           use this, as by default the right libraries
-                           will be queried with gsl-config.
   --with-silo              Use the SILO library to write visualisation
                            outputs.  Default: no.
   --with-silo-dir=DIR      See description of --with-sprng-dir.  This is
@@ -566,83 +562,84 @@ $ECHO -ne "\to generating \`Makefile.config'... " | tee -a config.log
 $ECHO "# Makefile.config generated from Makefile.config.in by configure" > Makefile.config
 $ECHO "" >> Makefile.config
 cat Makefile.config.in >> Makefile.config
-sed -i s/__TOOLCHAIN__/$TOOLCHAIN/ Makefile.config
+sed -i.bak s/__TOOLCHAIN__/$TOOLCHAIN/ Makefile.config
 if test "x$WITH_OPENMP" = "xtrue"
 then
-	sed -i s/__WITH_OPENMP__/true/ Makefile.config
+	sed -i.bak s/__WITH_OPENMP__/true/ Makefile.config
 else
-	sed -i s/__WITH_OPENMP__/false/ Makefile.config
+	sed -i.bak s/__WITH_OPENMP__/false/ Makefile.config
 fi
 if test "x$WITH_MPI" = "xtrue"
 then
-	sed -i s/__WITH_MPI__/true/ Makefile.config
-	sed -i s/__MPICC__/$WITH_MPICC/ Makefile.config
+	sed -i.bak s/__WITH_MPI__/true/ Makefile.config
+	sed -i.bak s/__MPICC__/$WITH_MPICC/ Makefile.config
 else
-	sed -i s/__WITH_MPI__/false/ Makefile.config
-	sed -i s/__MPICC__// Makefile.config
+	sed -i.bak s/__WITH_MPI__/false/ Makefile.config
+	sed -i.bak s/__MPICC__// Makefile.config
 fi
 if test "x$WITH_SPRNG" = "xtrue"
 then
-	sed -i s/__WITH_SPRNG__/true/ Makefile.config
+	sed -i.bak s/__WITH_SPRNG__/true/ Makefile.config
 else
-	sed -i s/__WITH_SPRNG__/false/ Makefile.config
+	sed -i.bak s/__WITH_SPRNG__/false/ Makefile.config
 fi
 if test "x$WITH_SILO" = "xtrue"
 then
-	sed -i s/__WITH_SILO__/true/ Makefile.config
+	sed -i.bak s/__WITH_SILO__/true/ Makefile.config
 else
-	sed -i s/__WITH_SILO__/false/ Makefile.config
+	sed -i.bak s/__WITH_SILO__/false/ Makefile.config
 fi
 if test "x$WITH_HDF5" = "xtrue"
 then
-	sed -i s/__WITH_HDF5__/true/ Makefile.config
+	sed -i.bak s/__WITH_HDF5__/true/ Makefile.config
 else
-	sed -i s/__WITH_HDF5__/false/ Makefile.config
+	sed -i.bak s/__WITH_HDF5__/false/ Makefile.config
 fi
 if test "x$WITH_MPITRACE" = "xtrue"
 then
-	sed -i s/__WITH_MPITRACE__/true/ Makefile.config
+	sed -i.bak s/__WITH_MPITRACE__/true/ Makefile.config
 else
-	sed -i s/__WITH_MPITRACE__/false/ Makefile.config
+	sed -i.bak s/__WITH_MPITRACE__/false/ Makefile.config
 fi
 if test "x$ENABLE_DEBUG" = "xtrue"
 then
-	sed -i s/__ENABLE_DEBUG__/true/ Makefile.config
+	sed -i.bak s/__ENABLE_DEBUG__/true/ Makefile.config
 else
-	sed -i s/__ENABLE_DEBUG__/false/ Makefile.config
+	sed -i.bak s/__ENABLE_DEBUG__/false/ Makefile.config
 fi
 if test "x$ENABLE_DOUBLE" = "xtrue"
 then
-	sed -i s/__ENABLE_DOUBLE__/true/ Makefile.config
+	sed -i.bak s/__ENABLE_DOUBLE__/true/ Makefile.config
 else
-	sed -i s/__ENABLE_DOUBLE__/false/ Makefile.config
+	sed -i.bak s/__ENABLE_DOUBLE__/false/ Makefile.config
 fi
 if test "x$ENABLE_PROFILE" = "xtrue"
 then
-	sed -i s/__ENABLE_PROFILE__/true/ Makefile.config
+	sed -i.bak s/__ENABLE_PROFILE__/true/ Makefile.config
 else
-	sed -i s/__ENABLE_PROFILE__/false/ Makefile.config
+	sed -i.bak s/__ENABLE_PROFILE__/false/ Makefile.config
 fi
-sed -i -e "s@__WITH_FFT__@$WITH_FFT@" Makefile.config
-sed -i -e "s@__CC__@$CC@" Makefile.config
-sed -i -e "s@__CFLAGS__@$CFLAGS@" Makefile.config
-sed -i -e "s@__CPPFLAGS__@$CPPFLAGS@" Makefile.config
-sed -i -e "s@__DEPCC__@$DEPCC@" Makefile.config
-sed -i -e "s@__LD__@$LD@" Makefile.config
-sed -i -e "s@__LDFLAGS__@$LDFLAGS@" Makefile.config
-sed -i -e "s@__AR__@$AR@" Makefile.config
-sed -i -e "s@__MAKE__@$MAKE@" Makefile.config
-sed -i -e "s@__WITH_SPRNG_DIR__@$WITH_SPRNG_DIR@" Makefile.config
-sed -i -e "s@__WITH_SPRNG_LIBS__@$WITH_SPRNG_LIBS@" Makefile.config
-sed -i -e "s@__WITH_FFT_DIR__@$WITH_FFT_DIR@" Makefile.config
-sed -i -e "s@__WITH_FFT_LIBS__@$WITH_FFT_LIBS@" Makefile.config
-sed -i -e "s@__WITH_SILO_DIR__@$WITH_SILO_DIR@" Makefile.config
-sed -i -e "s@__WITH_SILO_LIBS__@$WITH_SILO_LIBS@" Makefile.config
-sed -i -e "s@__WITH_HDF5_DIR__@$WITH_HDF5_DIR@" Makefile.config
-sed -i -e "s@__WITH_GSL_DIR__@$WITH_GSL_DIR@" Makefile.config
-sed -i -e "s@__WITH_GSL_LIBS__@$WITH_GSL_LIBS@" Makefile.config
-sed -i -e "s@__WITH_MPITRACE_DIR__@$WITH_MPITRACE_DIR@" Makefile.config
+sed -i.bak -e "s@__WITH_FFT__@$WITH_FFT@" Makefile.config
+sed -i.bak -e "s@__CC__@$CC@" Makefile.config
+sed -i.bak -e "s@__CFLAGS__@$CFLAGS@" Makefile.config
+sed -i.bak -e "s@__CPPFLAGS__@$CPPFLAGS@" Makefile.config
+sed -i.bak -e "s@__DEPCC__@$DEPCC@" Makefile.config
+sed -i.bak -e "s@__LD__@$LD@" Makefile.config
+sed -i.bak -e "s@__LDFLAGS__@$LDFLAGS@" Makefile.config
+sed -i.bak -e "s@__AR__@$AR@" Makefile.config
+sed -i.bak -e "s@__MAKE__@$MAKE@" Makefile.config
+sed -i.bak -e "s@__WITH_SPRNG_DIR__@$WITH_SPRNG_DIR@" Makefile.config
+sed -i.bak -e "s@__WITH_SPRNG_LIBS__@$WITH_SPRNG_LIBS@" Makefile.config
+sed -i.bak -e "s@__WITH_FFT_DIR__@$WITH_FFT_DIR@" Makefile.config
+sed -i.bak -e "s@__WITH_FFT_LIBS__@$WITH_FFT_LIBS@" Makefile.config
+sed -i.bak -e "s@__WITH_SILO_DIR__@$WITH_SILO_DIR@" Makefile.config
+sed -i.bak -e "s@__WITH_SILO_LIBS__@$WITH_SILO_LIBS@" Makefile.config
+sed -i.bak -e "s@__WITH_HDF5_DIR__@$WITH_HDF5_DIR@" Makefile.config
+sed -i.bak -e "s@__WITH_GSL_DIR__@$WITH_GSL_DIR@" Makefile.config
+sed -i.bak -e "s@__WITH_GSL_LIBS__@$WITH_GSL_LIBS@" Makefile.config
+sed -i.bak -e "s@__WITH_MPITRACE_DIR__@$WITH_MPITRACE_DIR@" Makefile.config
 $ECHO "done" | tee -a config.log
+rm -f Makefile.config.bak
 
 
 # Generate config.h
@@ -652,53 +649,54 @@ $ECHO "" >> config.h
 cat config.h.in >> config.h
 if test "x$WITH_OPENMP" = "xtrue"
 then
-	sed -i -e 's/undef WITH_OPENMP/define WITH_OPENMP 1/' config.h
+	sed -i.bak -e 's/undef WITH_OPENMP/define WITH_OPENMP 1/' config.h
 fi
 if test "x$WITH_MPI" = "xtrue"
 then
-	sed -i -e 's/undef WITH_MPI$/define WITH_MPI 1/' config.h
+	sed -i.bak -e 's/undef WITH_MPI$/define WITH_MPI 1/' config.h
 fi
 if test "x$WITH_SPRNG" = "xtrue"
 then
-	sed -i -e 's/undef WITH_SPRNG/define WITH_SPRNG 1/' config.h
+	sed -i.bak -e 's/undef WITH_SPRNG/define WITH_SPRNG 1/' config.h
 fi
 if test "x$WITH_FFT" = "xfftw2"
 then
-	sed -i -e 's/undef WITH_FFT_FFTW2/define WITH_FFT_FFTW2 1/' config.h
+	sed -i.bak -e 's/undef WITH_FFT_FFTW2/define WITH_FFT_FFTW2 1/' config.h
 elif test "x$WITH_FFT" = "xfftw3"
 then
-	sed -i -e 's/undef WITH_FFT_FFTW3/define WITH_FFT_FFTW3 1/' config.h
+	sed -i.bak -e 's/undef WITH_FFT_FFTW3/define WITH_FFT_FFTW3 1/' config.h
 fi
 if test "x$WITH_SILO" = "xtrue"
 then
-	sed -i -e 's/undef WITH_SILO/define WITH_SILO 1/' config.h
+	sed -i.bak -e 's/undef WITH_SILO/define WITH_SILO 1/' config.h
 fi
 if test "x$WITH_HDF5" = "xtrue"
 then
-	sed -i -e 's/undef WITH_HDF5/define WITH_HDF5 1/' config.h
+	sed -i.bak -e 's/undef WITH_HDF5/define WITH_HDF5 1/' config.h
 fi
 if test "x$WITH_MPITRACE" = "xtrue"
 then
-	sed -i -e 's/undef WITH_MPITRACE/define WITH_MPITRACE 1/' config.h
+	sed -i.bak -e 's/undef WITH_MPITRACE/define WITH_MPITRACE 1/' config.h
 fi
 if test "x$WITH_PROC_DIR" = "xtrue"
 then
-	sed -i -e 's/undef WITH_PROC_DIR/define WITH_PROC_DIR 1/' config.h
+	sed -i.bak -e 's/undef WITH_PROC_DIR/define WITH_PROC_DIR 1/' config.h
 fi
 if test "x$ENABLE_DOUBLE" = "xtrue"
 then
-	sed -i -e 's/undef ENABLE_DOUBLE/define ENABLE_DOUBLE 1/' config.h
+	sed -i.bak -e 's/undef ENABLE_DOUBLE/define ENABLE_DOUBLE 1/' config.h
 fi
 if test "x$ENABLE_WRITING" = "xtrue"
 then
-	sed -i -e 's/undef ENABLE_WRITING/define ENABLE_WRITING 1/' config.h
+	sed -i.bak -e 's/undef ENABLE_WRITING/define ENABLE_WRITING 1/' config.h
 fi
 if test "x$ENABLE_DEBUG" = "xtrue"
 then
-	sed -i -e 's/undef ENABLE_DEBUG/define ENABLE_DEBUG 1/' config.h
+	sed -i.bak -e 's/undef ENABLE_DEBUG/define ENABLE_DEBUG 1/' config.h
 fi
-sed -i -e "s@__NDIM_VALUE__@$NDIM_VALUE@" config.h
+sed -i.bak -e "s@__NDIM_VALUE__@$NDIM_VALUE@" config.h
 $ECHO "done" | tee -a config.log
+rm -f config.h.bak
 
 
 # Summarize the configuration
